### ISSUE TITLE
Create test in modifiedNLM

### ISSUE THREAD

**Issue by GustavoSolcia** [CIERMag-FFPaivaStudents/NLM#3]
Create test module with sigma estimate and Rician denoising

**Comment by Im-Kilroy** [comment]
It is done, I did a push into my branch.

**Comment by GustavoSolcia** [comment]
Still needs documentation improvements before merging

**Comment by Im-Kilroy** [comment]
I guess it is done, I added new names to the sample images and write a little about how to use test function. Besides I renamed the folder in my branch to modifiedNLM to merge with master branch later.

**Comment by Im-Kilroy** [comment]
New documentation added for module tests and new names for sample images.
